---
- name: Create Ceph pools with appropriate PG counts for small cluster
  ansible.builtin.command: >
    ceph osd pool create {{ item.name }} {{ item.pg_num | default(32) }}
  loop: "{{ ceph_pools }}"
  become: true
  register: pool_creation
  failed_when: 
    - pool_creation.rc != 0
    - "'already exists' not in pool_creation.stderr"
  changed_when: 
    - pool_creation.rc == 0
    - "'already exists' not in pool_creation.stderr"
  tags: ceph

- name: Set Ceph pool size and min_size
  ansible.builtin.command: >
    ceph osd pool set {{ item.name }} size {{ item.size }}
  loop: "{{ ceph_pools }}"
  become: true
  tags: ceph

- name: Set Ceph pool min_size
  ansible.builtin.command: >
    ceph osd pool set {{ item.name }} min_size {{ item.min_size }}
  loop: "{{ ceph_pools }}"
  become: true
  tags: ceph

- name: Create Ceph user for each pool with RBD profile
  ansible.builtin.command: >
    ceph auth get-or-create client.{{ item.name }} mon 'profile rbd' mgr 'allow rw' osd 'profile rbd pool={{ item.name }}'
  loop: "{{ ceph_pools }}"
  become: true
  tags: ceph

- name: Fetch Ceph user keyring for each pool
  ansible.builtin.command: >
    ceph auth get-key client.{{ item.name }}
  register: ceph_user_keys
  loop: "{{ ceph_pools }}"
  become: true
  tags: ceph
