---
# HAProxy installation and configuration tasks
- name: Debug inventory_hostname and ansible_hostname
  debug:
    msg: "Deploying HAProxy config on inventory_hostname={{ inventory_hostname }}, ansible_hostname={{ ansible_hostname }}"

- name: Install HAProxy
  apt:
    name: haproxy
    state: present
  become: true

- name: Deploy HAProxy configuration for dev.ankra.dev
  template:
    src: haproxy-dev.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: Reload haproxy
  become: true
  when: inventory_hostname == 'loadbalancer-dev'

- name: Deploy HAProxy configuration for prod.ankra.dev
  template:
    src: haproxy-prod.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: Reload haproxy
  become: true
  when: inventory_hostname == 'loadbalancer-prod'

- name: Ensure handlers are present
  meta: flush_handlers

- name: Ensure HAProxy is started and enabled
  service:
    name: haproxy
    state: started
    enabled: true
  become: true

# Firewall configuration for HAProxy
- name: Allow HTTP traffic on port 80
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    jump: ACCEPT
  become: true

- name: Allow HTTPS traffic on port 443
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    jump: ACCEPT
  become: true

- name: Allow NATS traffic on port 4222
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "4222"
    jump: ACCEPT
  become: true

- name: Allow HAProxy stats on port 8404
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "8404"
    jump: ACCEPT
  become: true

- name: Install iptables-persistent package
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    update_cache: yes
  become: true

- name: Ensure /etc/iptables directory exists
  ansible.builtin.file:
    path: /etc/iptables
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  become: true