---
- name: Setup OS, Network, and Users
  hosts: public_nodes
  become: true
  roles:
    - role: os
      tags: os
    - role: network
      tags: network
    - role: admin
      tags: admin

- name: Configure HAProxy nodes
  hosts: haproxy
  become: true
  roles:
    - role: haproxy
      tags: haproxy
    - role: security
      tags: security
    - role: admin
      tags: admin

- name: Setup Proxmox Infrastructure
  hosts: proxmox
  become: true
  roles:
    - role: proxmox
      tags: proxmox
    - role: proxmox_interfaces
      tags: proxmox_interfaces
    - role: proxmox_terraform
      tags: proxmox_terraform
    - role: admin
      tags: admin

- name: Setup Proxmox Cluster and Storage
  hosts: proxmox
  become: true
  roles:
    - role: proxmox_cluster
      tags: proxmox_cluster
    - role: proxmox_ceph
      tags: proxmox_ceph

- name: Setup Users on Development Environment
  hosts: development
  become: true
  roles:
    - role: admin
      tags: admin

- name: Setup Users on Production Environment
  hosts: production
  become: true
  roles:
    - role: admin
      tags: admin

- name: Setup Users on Infrastructure Environment
  hosts: infrastructure
  become: true
  roles:
    - role: admin
      tags: admin