---
- name: Setup OS, and Network
  hosts: public_nodes
  become: true
  roles:
    - os
    - network

- name: Configure HAProxy nodes
  hosts: haproxy
  become: true
  roles:
    - haproxy
    - security

- name: Setup Proxmox Interfaces
  hosts: proxmox
  become: true
  roles:
    - proxmox_interfaces