---
- name: Setup OS, and Network
  hosts: public_nodes
  become: true
  roles:
    - role: os
      tags: os
    - role: network
      tags: network

- name: Configure HAProxy nodes
  hosts: haproxy
  become: true
  roles:
    - role: haproxy
      tags: haproxy
    - role: security
      tags: security

- name: Setup Proxmox Interfaces
  hosts: proxmox
  become: true
  roles:
    - role: proxmox_interfaces
      tags: proxmox_interfaces
    - role: proxmox_ceph
      tags: proxmox_ceph