---
# Virt-UK specific playbook focusing on Proxmox cluster setup
- name: Setup Proxmox Infrastructure
  hosts: proxmox
  become: true
  roles:
    - role: os
      tags: os
    - role: network  
      tags: network
    - role: admin
      tags: admin
    - role: proxmox
      tags: proxmox
    - role: proxmox_interfaces
      tags: proxmox_interfaces

- name: Setup Proxmox Cluster and Storage
  hosts: proxmox
  become: true
  roles:
    - role: proxmox_cluster
      tags: proxmox_cluster
    - role: proxmox_ceph
      tags: proxmox_ceph
