---
node_exporter_version: "1.7.0"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_bin_path: /usr/local/bin/node_exporter
node_exporter_service_path: /etc/systemd/system/node_exporter.service
