---
- name: Download node_exporter binary
  ansible.builtin.get_url:
    url: "{{ node_exporter_download_url }}"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'
  become: true

- name: Extract node_exporter binary
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/
    remote_src: yes
  become: true

- name: Copy node_exporter binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    remote_src: yes
    mode: '0755'
  become: true

- name: Create node_exporter systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: "{{ node_exporter_service_path }}"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Enable and start node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
  become: true
