ens19_netmask: 26
ens19_gateway: 51.195.238.228

dhcp_interfaces:
  - name: ens18
  - name: ens19

cloudflare_dns: 1.1.1.1

ansible_ssh_common_args: '-o ProxyJump=root@51.89.192.98'
ansible_user: debian
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

# Proxmox configuration for UK (latest)
proxmox_version: "9.0.3"
ceph_version: "squid"  # Latest Ceph version for newer Proxmox

# Proxmox cluster configuration for production
proxmox_cluster_enabled: true
proxmox_cluster_name: "virt-uk-cluster"
production_mode: false
min_cluster_nodes: 1

# Network Architecture for virt-uk:
# vmbr0 -> Public network (172.16.20.0/24) - existing management network
# vmbr1 -> Private network between Proxmox nodes (172.16.21.0/24) - VLAN 4000 for cluster communication
# vmbr2 -> VM network (172.16.22.0/24) - Network for virtual machines

# Ceph configuration for virt-uk cluster (using private network VLAN 4000)
ceph_cluster_enabled: true
ceph_network: "172.16.21.0/24"
ceph_public_network: "172.16.21.0/24"
ceph_cluster_network: "172.16.20.0/24"
ceph_osd_pool_default_size: 3
ceph_osd_pool_default_min_size: 2

# Production settings
configure_ha: true
configure_fencing: false

ceph_pools:
  - name: infra_k8s_data
    pg_num: 32
    size: 2
    min_size: 1
  - name: virt_uk_data
    pg_num: 32
    size: 3
    min_size: 2
  - name: virt_uk_vms
    pg_num: 32
    size: 3
    min_size: 2

# Admin users configuration
admin_users:
  - name: mark
    public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH0lTjp4WvJ4tA60xLQPpNXpAo3lKymXHGzvk3UpQOUp mark@ankra"
    sudo: true
    shell: /bin/bash
    groups: []
  - name: mattias
    public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBbr+bc5f+n5kIIm++SkvmZ2LX2Coff+TO+DC69XWbfi mattias@ankra"
    sudo: true
    shell: /bin/bash
    groups: []