ens19_netmask: 26
ens19_gateway: 168.119.65.1

dhcp_interfaces:
  - name: ens18
  - name: ens19

cloudflare_dns: 1.1.1.1

proxmox_interfaces:
  - name: vmbr1
    cidr: 172.16.10.1/24
  - name: vmbr2
    cidr: 10.1.100.1/24
  - name: vmbr3
    cidr: 10.1.110.1/24
ansible_ssh_common_args: '-o ProxyJump=root@168.119.65.46'
ansible_user: debian
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

ceph_pools:
  - name: infra_k8s_data
    size: 2
    min_size: 1
  - name: prod_k8s_data
    size: 2
    min_size: 1
  - name: dev_k8s_data
    size: 2
    min_size: 1